### ISSUE TITLE
Add Content Creation Guidelines in the README.md

### ISSUE THREAD

**Issue by SanditZZ** [SanditZZ/cat-docs#10]
Take a look at the official VitePress docs here about writing markdown: https://vitepress.dev/guide/markdown
Add another section under "Content Creation Guidelines"
You can come up with your own version of how to add a page to an existing section.
Please keep it simple and concise 👍

**Comment by ghost** [comment]
hey @SanditZZ  I would you like to work on this issue, please assign it to me.
